name: online_shop
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'




dependencies:
  flutter:
    sdk: flutter
  persian_datetime_picker:
  cupertino_icons: ^1.0.2
  dio : ^5.1.1
  lottie: 
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1  
  intl: ^0.18.1
  webview_universal: ^0.0.5
  url_launcher: ^6.2.1
  connectivity_plus :



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/slides/
    - assets/lottie/
    - assets/images/empty.png



  
  fonts:
    - family: yekan
      fonts:
        - asset: assets/font/yekan.ttf
        
